### ISSUE TITLE
Remove hard coded path

### ISSUE THREAD

**Issue by wilke** [JDACS4C-IMPROVE/NIHGCN#6]
This works only in a very specific environment, suggest removing it and replace with parameter or env variable.

https://github.com/JDACS4C-IMPROVE/NIHGCN/blob/ea9a9be942e8d386713c7d1296aad237c7a29f7e/candle_glue.sh#L4

**Comment by chian** [comment]
I think I fixed it. Tested and runs the same as before.

**Comment by wilke** [comment]
I am closing this issue and restarting testing and integration from scratch for the next release.
